// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rest

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockservice creates a new instance of Mockservice. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockservice(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockservice {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Mockservice{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Mockservice is an autogenerated mock type for the service type
type Mockservice struct {
	mock.Mock
}

type Mockservice_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockservice) EXPECT() *Mockservice_Expecter {
	return &Mockservice_Expecter{mock: &_m.Mock}
}

// HealthReady provides a mock function for the type Mockservice
func (_mock *Mockservice) HealthReady() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthReady")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Mockservice_HealthReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthReady'
type Mockservice_HealthReady_Call struct {
	*mock.Call
}

// HealthReady is a helper method to define mock.On call
func (_e *Mockservice_Expecter) HealthReady() *Mockservice_HealthReady_Call {
	return &Mockservice_HealthReady_Call{Call: _e.mock.On("HealthReady")}
}

func (_c *Mockservice_HealthReady_Call) Run(run func()) *Mockservice_HealthReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mockservice_HealthReady_Call) Return(b bool) *Mockservice_HealthReady_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Mockservice_HealthReady_Call) RunAndReturn(run func() bool) *Mockservice_HealthReady_Call {
	_c.Call.Return(run)
	return _c
}
