// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/viczem/userhub/services/userhub/internal/domain"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockRepository
func (_mock *MockRepository) Close(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockRepository_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) Close(ctx any) *MockRepository_Close_Call {
	return &MockRepository_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockRepository_Close_Call) Run(run func(ctx context.Context)) *MockRepository_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Close_Call) Return() *MockRepository_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepository_Close_Call) RunAndReturn(run func(ctx context.Context)) *MockRepository_Close_Call {
	_c.Run(run)
	return _c
}

// Commit provides a mock function for the type MockRepository
func (_mock *MockRepository) Commit(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockRepository_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) Commit(ctx any) *MockRepository_Commit_Call {
	return &MockRepository_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockRepository_Commit_Call) Run(run func(ctx context.Context)) *MockRepository_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Commit_Call) Return(err error) *MockRepository_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Commit_Call) RunAndReturn(run func(ctx context.Context) error) *MockRepository_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRuntimeSession provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateRuntimeSession(ctx context.Context, session *domain.RuntimeSession) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for CreateRuntimeSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.RuntimeSession) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateRuntimeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRuntimeSession'
type MockRepository_CreateRuntimeSession_Call struct {
	*mock.Call
}

// CreateRuntimeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.RuntimeSession
func (_e *MockRepository_Expecter) CreateRuntimeSession(ctx any, session any) *MockRepository_CreateRuntimeSession_Call {
	return &MockRepository_CreateRuntimeSession_Call{Call: _e.mock.On("CreateRuntimeSession", ctx, session)}
}

func (_c *MockRepository_CreateRuntimeSession_Call) Run(run func(ctx context.Context, session *domain.RuntimeSession)) *MockRepository_CreateRuntimeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.RuntimeSession
		if args[1] != nil {
			arg1 = args[1].(*domain.RuntimeSession)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateRuntimeSession_Call) Return(err error) *MockRepository_CreateRuntimeSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateRuntimeSession_Call) RunAndReturn(run func(ctx context.Context, session *domain.RuntimeSession) error) *MockRepository_CreateRuntimeSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRuntimeSession provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteRuntimeSession(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRuntimeSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteRuntimeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRuntimeSession'
type MockRepository_DeleteRuntimeSession_Call struct {
	*mock.Call
}

// DeleteRuntimeSession is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) DeleteRuntimeSession(ctx any) *MockRepository_DeleteRuntimeSession_Call {
	return &MockRepository_DeleteRuntimeSession_Call{Call: _e.mock.On("DeleteRuntimeSession", ctx)}
}

func (_c *MockRepository_DeleteRuntimeSession_Call) Run(run func(ctx context.Context)) *MockRepository_DeleteRuntimeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteRuntimeSession_Call) Return(err error) *MockRepository_DeleteRuntimeSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteRuntimeSession_Call) RunAndReturn(run func(ctx context.Context) error) *MockRepository_DeleteRuntimeSession_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockRepository
func (_mock *MockRepository) Rollback(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockRepository_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) Rollback(ctx any) *MockRepository_Rollback_Call {
	return &MockRepository_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockRepository_Rollback_Call) Run(run func(ctx context.Context)) *MockRepository_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Rollback_Call) Return(err error) *MockRepository_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Rollback_Call) RunAndReturn(run func(ctx context.Context) error) *MockRepository_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDatabase creates a new instance of MockDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabase[R Repository](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabase[R] {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDatabase[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDatabase is an autogenerated mock type for the Database type
type MockDatabase[R Repository] struct {
	mock.Mock
}

type MockDatabase_Expecter[R Repository] struct {
	mock *mock.Mock
}

func (_m *MockDatabase[R]) EXPECT() *MockDatabase_Expecter[R] {
	return &MockDatabase_Expecter[R]{mock: &_m.Mock}
}

// NewRepository provides a mock function for the type MockDatabase
func (_mock *MockDatabase[R]) NewRepository(ctx context.Context) (R, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NewRepository")
	}

	var r0 R
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (R, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) R); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(R)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_NewRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewRepository'
type MockDatabase_NewRepository_Call[R Repository] struct {
	*mock.Call
}

// NewRepository is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter[R]) NewRepository(ctx any) *MockDatabase_NewRepository_Call[R] {
	return &MockDatabase_NewRepository_Call[R]{Call: _e.mock.On("NewRepository", ctx)}
}

func (_c *MockDatabase_NewRepository_Call[R]) Run(run func(ctx context.Context)) *MockDatabase_NewRepository_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatabase_NewRepository_Call[R]) Return(v R, err error) *MockDatabase_NewRepository_Call[R] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDatabase_NewRepository_Call[R]) RunAndReturn(run func(ctx context.Context) (R, error)) *MockDatabase_NewRepository_Call[R] {
	_c.Call.Return(run)
	return _c
}

// Ready provides a mock function for the type MockDatabase
func (_mock *MockDatabase[R]) Ready() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabase_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type MockDatabase_Ready_Call[R Repository] struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
func (_e *MockDatabase_Expecter[R]) Ready() *MockDatabase_Ready_Call[R] {
	return &MockDatabase_Ready_Call[R]{Call: _e.mock.On("Ready")}
}

func (_c *MockDatabase_Ready_Call[R]) Run(run func()) *MockDatabase_Ready_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabase_Ready_Call[R]) Return(err error) *MockDatabase_Ready_Call[R] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabase_Ready_Call[R]) RunAndReturn(run func() error) *MockDatabase_Ready_Call[R] {
	_c.Call.Return(run)
	return _c
}
